# serverless.yml
component: 
service: peterportal-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  timeout: 10
  memorySize: 512
  logRetentionInDays: 30
  apiGateway:
    binaryMediaTypes:
      - 'image/*'
package:
  excludeDevDependencies: true
  individually: true
  include:
     - docs-site/**/*
     - db/*.sqlite
     - public/**/*

plugins:
  - serverless-api-gateway-throttling
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  # - serverless-domain-manager
  - serverless-plugin-lambda-insights
  - serverless-plugin-typescript 


custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 50
  # customDomain: 
  #   domainName: api.peterportal.org
  #   basepath: ""
  #   certificateName: "*.peterportal.org"
  #   createRoute53Record: true
  #   stage: ${self:provider.stage}
  lambdaInsights:
    defaultLambdaInsights: true #enables Lambda Insights for all functions


functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY