version: 2.1

commands:
  create-env-file:
    steps:
      - run:
          name: Create ENV File
          command: |
            printf "NODE_ENV='$NODE_ENV'\nMOESIF_KEY='$MOESIF_KEY'
            SENTRY_DSN='$SENTRY_DSN'" > .env
  build-docs:
    steps:
      - run:
          name: Install dependencies
          command: pip install mkdocs-material
      - run: 
          name: Build docs
          command: mkdocs build -d docs-site

workflows: 
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
              - serverless-test

jobs:
  build:
    docker:
      - image: circleci/node:12.22
    steps:
      - checkout
      - create-env-file
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g --unsafe-perm serverless
            npm install --dev

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: 
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Deploy application
          command: sls deploy --stage prod