version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
  serverless: circleci/serverless-framework@1.0
  lambda_ci: appfolio/lambda_ci@0.3.0

commands:
  create-env-file:
    steps:
      - run:
          name: Create ENV File
          command: |
            printf "NODE_ENV='$NODE_ENV'\nMOESIF_KEY='$MOESIF_KEY'
            SENTRY_DSN='$SENTRY_DSN'" > .env
  build-docs:
    steps:
      - run:
          name: Install Python dependencies
          command: pip install -r docs_requirements.txt
      - run: 
          name: Build docs
          command: mkdocs build -d docs-site

workflows: 
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - typescript-rewrite

jobs:
  build:
    executor: serverless/default
    steps:
      - checkout
      - create-env-file
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v4-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-{{ .Branch }}

      - run:
          name: Install Serverless CLI 
          command: |
            npm install -g serverless

      - run: 
          name: Install dependencies
          command: |
            npm install --also=dev
      #Build the docs html files
      - build-docs
      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

      - run: 
          name: Run tests with coverage
          command: npm test

      - aws-cli/setup

      - run:
          name: Deploy application
          command: sls deploy